# Generated by Django 5.2 on 2025-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='app1.student'),
        ),
    ]
