# Generated by Django 5.2 on 2025-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_courses_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='enrolled_students', to='app1.course'),
        ),
    ]
